# Generated by Django 4.2.27 on 2025-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_ban_reason_user_is_banned_alter_note_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='static_question_status',
            field=models.CharField(choices=[('unfinished', 'Unfinished'), ('finished', 'Finished')], default='unfinished', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='static_questions_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_static_questions',
            field=models.IntegerField(default=0),
        ),
    ]
