# Generated by Django 6.0.4 on 2026-04-14

from django.db import migrations, models


def seed_user_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')

    User.objects.filter(is_banned=True).update(role='ban')
    User.objects.filter(is_banned=False).update(role='user')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_note_id_alter_studysession_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('ban', 'Ban'),
                    ('pro', 'Pro'),
                    ('lite', 'Lite'),
                    ('user', 'User'),
                    ('enterprise', 'Enterprise'),
                ],
                default='ban',
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_user_roles, noop_reverse),
    ]