# Generated by Django 6.0 on 2025-12-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_analytics_id_alter_quiz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('math', 'Mathematics'), ('higher_math', 'Higher Mathematics'), ('bangla_1st', 'Bangla 1st Paper'), ('bangla_2nd', 'Bangla 2nd Paper'), ('english_1st', 'English 1st Paper'), ('english_2nd', 'English 2nd Paper'), ('biology', 'Biology'), ('ict', 'ICT'), ('science', 'Science'), ('bangladesh_global', 'Bangladesh & Global Studies'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('accounting', 'Accounting'), ('finance', 'Finance & Banking'), ('business', 'Business Entrepreneurship'), ('economics', 'Economics'), ('general_science', 'General Science')], max_length=50),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bengali_title', models.CharField(blank=True, max_length=100)),
                ('subject_code', models.CharField(max_length=50, unique=True)),
                ('class_level', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')])),
                ('stream', models.CharField(blank=True, max_length=50, null=True)),
                ('is_compulsory', models.BooleanField(default=True)),
                ('icon', models.CharField(default='📚', max_length=10)),
                ('color', models.CharField(default='bg-blue-100', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['class_level', 'name'],
                'unique_together': {('subject_code', 'class_level')},
            },
        ),
    ]
