# Generated by Django 4.2.27 on 2025-12-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0006_alter_subject_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userperformance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserQuizProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('math', 'Mathematics'), ('higher_math', 'Higher Mathematics'), ('bangla_1st', 'Bangla 1st Paper'), ('bangla_2nd', 'Bangla 2nd Paper'), ('english_1st', 'English 1st Paper'), ('english_2nd', 'English 2nd Paper'), ('biology', 'Biology'), ('ict', 'ICT'), ('science', 'Science'), ('bangladesh_global', 'Bangladesh & Global Studies'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('accounting', 'Accounting'), ('finance', 'Finance & Banking'), ('business', 'Business Entrepreneurship'), ('economics', 'Economics'), ('general_science', 'General Science')], max_length=50)),
                ('class_level', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')])),
                ('static_questions_completed', models.IntegerField(default=0)),
                ('total_static_questions', models.IntegerField(default=0)),
                ('static_completion_percentage', models.FloatField(default=0.0)),
                ('ai_questions_answered', models.IntegerField(default=0)),
                ('ai_questions_correct', models.IntegerField(default=0)),
                ('current_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('status', models.CharField(choices=[('static', 'Completing Static Questions'), ('ai_active', 'AI Questions Active'), ('finished', 'All Questions Finished')], default='static', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'subject', 'class_level')},
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('math', 'Mathematics'), ('higher_math', 'Higher Mathematics'), ('bangla_1st', 'Bangla 1st Paper'), ('bangla_2nd', 'Bangla 2nd Paper'), ('english_1st', 'English 1st Paper'), ('english_2nd', 'English 2nd Paper'), ('biology', 'Biology'), ('ict', 'ICT'), ('science', 'Science'), ('bangladesh_global', 'Bangladesh & Global Studies'), ('history', 'History'), ('geography', 'Geography'), ('civics', 'Civics'), ('accounting', 'Accounting'), ('finance', 'Finance & Banking'), ('business', 'Business Entrepreneurship'), ('economics', 'Economics'), ('general_science', 'General Science')], max_length=50)),
                ('class_level', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')])),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer'), ('long', 'Long Answer')], default='mcq', max_length=10)),
                ('options', models.JSONField(default=dict)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('user_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('generation_batch', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['generated_at'],
                'indexes': [models.Index(fields=['user', 'subject', 'is_answered'], name='quizzes_aig_user_id_7f550a_idx')],
            },
        ),
    ]
