# Generated by Django 4.2.27 on 2025-12-24 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0007_alter_analytics_id_alter_quiz_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userperformance',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AlterUniqueTogether(
            name='userperformance',
            unique_together={('user', 'subject')},
        ),
    ]
