# Generated by Django 6.0.4 on 2026-04-17 12:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_role'),
        ('quizzes', '0010_alter_aigeneratedquestion_id_alter_analytics_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrijonshilQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=80)),
                ('class_level', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')])) ,
                ('chapter', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('uddipok', models.TextField()),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('question_4', models.TextField()),
                ('model_answer_1', models.TextField(blank=True)),
                ('model_answer_2', models.TextField(blank=True)),
                ('model_answer_3', models.TextField(blank=True)),
                ('model_answer_4', models.TextField(blank=True)),
                ('provider_used', models.CharField(default='auto', max_length=30)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srijonshil_sets', to='accounts.user')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'subject', 'class_level'], name='quizzes_sri_user_id_6145d9_idx'),
                    models.Index(fields=['user', 'is_submitted', 'created_at'], name='quizzes_sri_user_id_802147_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SrijonshilAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.TextField(blank=True)),
                ('answer_2', models.TextField(blank=True)),
                ('answer_3', models.TextField(blank=True)),
                ('answer_4', models.TextField(blank=True)),
                ('feedback_1', models.TextField(blank=True)),
                ('feedback_2', models.TextField(blank=True)),
                ('feedback_3', models.TextField(blank=True)),
                ('feedback_4', models.TextField(blank=True)),
                ('overall_feedback', models.TextField(blank=True)),
                ('marks_1', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('marks_2', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('marks_3', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(3.0)])),
                ('marks_4', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)])),
                ('total_marks', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('evaluation_source', models.CharField(default='rule_based', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.srijonshilquestionset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srijonshil_attempts', to='accounts.user')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'question_set')},
                'indexes': [
                    models.Index(fields=['user', 'submitted_at'], name='quizzes_sri_user_id_6f9d3f_idx'),
                    models.Index(fields=['question_set', 'submitted_at'], name='quizzes_sri_questio_6b6687_idx'),
                ],
            },
        ),
    ]
