# Generated by Django 6.0 on 2025-12-25 13:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('memory_pattern', 'Memory Pattern'), ('memory_matrix', 'Memory Matrix'), ('math_quiz', 'Math Challenge'), ('equation_storm', 'Equation Storm'), ('word_puzzle', 'Word Puzzle'), ('pattern_matching', 'Pattern Match'), ('pathfinder', 'Pathfinder'), ('infinite_loop', 'Infinite Loop')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_grade', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('max_grade', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('base_points', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('criteria', models.JSONField()),
                ('points', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_level', models.IntegerField(default=1)),
                ('session_score', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
            ],
            options={
                'ordering': ['-last_played'],
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('score', models.IntegerField()),
                ('time_taken', models.FloatField()),
                ('accuracy', models.FloatField(default=100.0)),
                ('success', models.BooleanField(default=False)),
                ('bonus_points', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.gamesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('total_score', models.IntegerField(default=0)),
                ('total_games_played', models.IntegerField(default=0)),
                ('achievements', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_score'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.playerprofile'),
        ),
        migrations.CreateModel(
            name='GameLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_score', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-highest_score'],
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to='games.playerprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('global', 'Global'), ('per_game', 'Per Game'), ('per_grade', 'Per Grade'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='per_game', max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('highest_level', models.IntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)])),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.playerprofile')),
            ],
            options={
                'ordering': ['-total_score', '-highest_level'],
                'indexes': [models.Index(fields=['leaderboard_type', 'game', '-total_score'], name='games_leade_leaderb_3dadfe_idx'), models.Index(fields=['grade', '-total_score'], name='games_leade_grade_e7017f_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gamesession',
            unique_together={('player', 'game')},
        ),
    ]
