# Generated by Django 6.0.4 on 2026-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('memory_pattern', 'Memory Pattern'), ('ship_find', 'Ship Find'), ('number_hunt', 'Number Hunt'), ('image_dragger', 'Image Dragger'), ('memory_matrix', 'Memory Matrix'), ('math_quiz', 'Math Challenge'), ('equation_storm', 'Equation Storm'), ('word_puzzle', 'Word Puzzle'), ('pattern_matching', 'Pattern Match'), ('pathfinder', 'Pathfinder'), ('infinite_loop', 'Infinite Loop')], max_length=50, unique=True),
        ),
    ]
