"""
Django settings for medhabangla project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Always load backend/.env regardless of process working directory.
load_dotenv(BASE_DIR / '.env')


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name, str(default))
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_csv(name: str, default: str = '') -> list[str]:
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_csv('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Ensure container/internal health checks do not fail on host validation
# when production ALLOWED_HOSTS is domain-only.
for internal_host in ('localhost', '127.0.0.1'):
    if internal_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(internal_host)


# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for WebSocket support
    'unfold',  # Unfold admin theme
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'channels',  # WebSocket support
    'accounts',
    'quizzes',
    'books',
    'games',
    'ai',
    'chat',
    'academics',
    'translator',  # English-Bangla Translator with PWA support
    'billing',
]

# Custom user model
AUTH_USER_MODEL = 'accounts.User'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'medhabangla.middleware.DatabaseConnectionMiddleware',  # Custom DB connection management
]
ROOT_URLCONF = 'medhabangla.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medhabangla.wsgi.application'

# ASGI application for WebSocket support
ASGI_APPLICATION = 'medhabangla.asgi.application'

# Channels configuration
REDIS_URL = os.getenv('REDIS_URL', '')

CHANNEL_LAYERS = {
    'default': {
        # Use Redis for production
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [REDIS_URL or 'redis://127.0.0.1:6379/0'],
        },
    } if REDIS_URL else {
        # Use in-memory channel layer for development
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Supports:
# - SQLite local mode (USE_SQLITE=True)
# - Docker PostgreSQL service (DB_HOST=db)
# - Managed PostgreSQL (for example DigitalOcean managed database)
if env_bool('USE_SQLITE', False):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    use_postgres = env_bool('DOCKER_ENV', False) or bool(os.getenv('DB_HOST'))

    if use_postgres:
        db_options = {
            'connect_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '10')),
            'options': os.getenv('DB_OPTIONS', '-c statement_timeout=30000'),
            'keepalives': int(os.getenv('DB_KEEPALIVES', '1')),
            'keepalives_idle': int(os.getenv('DB_KEEPALIVES_IDLE', '30')),
            'keepalives_interval': int(os.getenv('DB_KEEPALIVES_INTERVAL', '10')),
            'keepalives_count': int(os.getenv('DB_KEEPALIVES_COUNT', '5')),
        }

        db_sslmode = os.getenv('DB_SSLMODE', 'prefer').strip()
        db_sslrootcert = os.getenv('DB_SSLROOTCERT', '').strip()

        if db_sslmode:
            db_options['sslmode'] = db_sslmode

        if db_sslrootcert:
            db_options['sslrootcert'] = db_sslrootcert

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME', 'medhabangla_db'),
                'USER': os.getenv('DB_USER', 'medhabangla_user'),
                'PASSWORD': os.getenv('DB_PASSWORD', ''),
                'HOST': os.getenv('DB_HOST', 'db'),
                'PORT': os.getenv('DB_PORT', '5432'),
                'OPTIONS': db_options,
                'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '300')),
                'CONN_HEALTH_CHECKS': True,
                'ATOMIC_REQUESTS': env_bool('DB_ATOMIC_REQUESTS', False),
            }
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = env_csv('CORS_ALLOWED_ORIGINS', '')

CSRF_TRUSTED_ORIGINS = env_csv('CSRF_TRUSTED_ORIGINS', '')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', True)

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    X_FRAME_OPTIONS = 'SAMEORIGIN'

# WorkOS settings
WORKOS_API_KEY = os.getenv('WORKOS_API_KEY')
WORKOS_CLIENT_ID = os.getenv('WORKOS_CLIENT_ID')
WORKOS_REDIRECT_URI = os.getenv(
    'WORKOS_REDIRECT_URI',
    f"{os.getenv('FRONTEND_URL', 'http://localhost:5173')}/auth/callback"
)

# Stripe payment settings
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '').strip()
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '').strip()
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '').strip()

_frontend_url = os.getenv('FRONTEND_URL', 'http://localhost:5173').rstrip('/')
STRIPE_SUCCESS_URL = os.getenv('STRIPE_SUCCESS_URL', f'{_frontend_url}/plans').strip()
STRIPE_CANCEL_URL = os.getenv('STRIPE_CANCEL_URL', f'{_frontend_url}/plans').strip()

# Auth redirect safety: when login form omits a `next` value, avoid Django's
# default /accounts/profile/ target (not present in this project).
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/admin/login/'

# Groq AI settings
GROQ_API_KEY = os.getenv('GROQ_API_KEY')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'llama-3.3-70b-versatile')

# Alibaba DashScope (Qwen) settings
ALIBABA_API_KEY = os.getenv('ALIBABA_API_KEY')

# Google Gemini API settings
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')  # Legacy single key

# Multiple Gemini API Keys for rotation (comma-separated)
GEMINI_API_KEYS_STR = os.getenv('GEMINI_API_KEYS', '')
if GEMINI_API_KEYS_STR:
    GEMINI_API_KEYS = [key.strip() for key in GEMINI_API_KEYS_STR.split(',') if key.strip()]
else:
    # Fallback to single key if multiple keys not provided
    GEMINI_API_KEYS = [GEMINI_API_KEY] if GEMINI_API_KEY else []

# 8x8 JaaS (Video Call) settings
JAAS_DOMAIN = os.getenv('JAAS_DOMAIN', '8x8.vc').strip() or '8x8.vc'
JAAS_APP_ID = os.getenv('JAAS_APP_ID', '').strip()
JAAS_KID = os.getenv('JAAS_KID', '').strip()
JAAS_PRIVATE_KEY = os.getenv('JAAS_PRIVATE_KEY', '').replace('\\n', '\n').strip()
JAAS_JWT_TTL_SECONDS = int(os.getenv('JAAS_JWT_TTL_SECONDS', '3600'))
JAAS_REQUIRE_AUTH_TOKEN = env_bool('JAAS_REQUIRE_AUTH_TOKEN', False)

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files, PDFs, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Google Drive Configuration for Chat File Storage
USE_GOOGLE_DRIVE = env_bool('USE_GOOGLE_DRIVE', False)
GOOGLE_DRIVE_CREDENTIALS_JSON = os.getenv('GOOGLE_DRIVE_CREDENTIALS_JSON', '')
GOOGLE_DRIVE_FOLDER_ID = os.getenv('GOOGLE_DRIVE_FOLDER_ID', '')
GOOGLE_DRIVE_PUBLIC_FILES = env_bool('GOOGLE_DRIVE_PUBLIC_FILES', True)

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Unfold UI Config
UNFOLD = {
    'SITE_TITLE': 'SOPNA Admin',
    'SITE_HEADER': 'SOPNA',
    'SITE_URL': '/',
    'SITE_ICON': lambda request: 'https://cdn-icons-png.flaticon.com/512/8066/8066115.png',
    'SITE_SYMBOL': 'school',  # Material symbol
    'ENVIRONMENT': 'medhabangla.dashboard.environment_callback',
    'DASHBOARD_CALLBACK': 'medhabangla.dashboard.dashboard_callback',
    'THEME': 'system',  # 'system' allows light/dark toggle mechanism to appear in unfold
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'COLORS': {
        'primary': {
            '50': '239 246 255',
            '100': '219 234 254',
            '200': '191 219 254',
            '300': '147 197 253',
            '400': '96 165 250',
            '500': '59 130 246',
            '600': '37 99 235',
            '700': '29 78 216',
            '800': '30 64 175',
            '900': '30 58 138',
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Dashboard & Users"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard Analytics"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("User Accounts"),
                        "icon": "group",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                ],
            },
            {
                "title": _("Learning Content"),
                "separator": True,
                "items": [
                    {
                        "title": _("Books Library"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:books_book_changelist"),
                    },
                    {
                        "title": _("Quizzes & Tests"),
                        "icon": "quiz",
                        "link": reverse_lazy("admin:quizzes_quiz_changelist"),
                    },
                ],
            },
            {
                "title": _("Interaction & AI"),
                "separator": True,
                "items": [
                    {
                        "title": _("AI Chat Sessions"),
                        "icon": "smart_toy",
                        "link": reverse_lazy("admin:ai_aichatsession_changelist"),
                    },
                    {
                        "title": _("Messenger"),
                        "icon": "chat",
                        "link": reverse_lazy("admin:chat_message_changelist"),
                    },
                    {
                        "title": _("Gamification"),
                        "icon": "sports_esports",
                        "link": reverse_lazy("admin:games_gamesession_changelist"),
                    },
                ],
            },
            {
                "title": _("Billing & System"),
                "separator": True,
                "items": [
                    {
                        "title": _("Plans"),
                        "icon": "sell",
                        "link": reverse_lazy("admin:billing_plan_changelist"),
                    },
                    {
                        "title": _("Plan Purchases"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:billing_planpurchase_changelist"),
                    },
                    {
                        "title": _("System Health"),
                        "icon": "monitor_heart",
                        "link": reverse_lazy("admin:billing_systemhealthstatus_changelist"),
                    },
                ],
            },
        ],
    },
}
