# Generated by Django 6.0.4 on 2026-04-11 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='emoji or icon name', max_length=50)),
                ('color', models.CharField(blank=True, help_text='hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dictionary Categories',
            },
        ),
        migrations.CreateModel(
            name='TranslationDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(db_index=True, max_length=500)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='en', max_length=2)),
                ('target_text', models.CharField(db_index=True, max_length=500)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='bn', max_length=2)),
                ('meaning', models.TextField(blank=True, max_length=1000)),
                ('word_type', models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('phrase', 'Phrase')], max_length=20)),
                ('example_english', models.TextField(blank=True, max_length=500)),
                ('example_bangla', models.TextField(blank=True, max_length=500)),
                ('context', models.CharField(blank=True, help_text="e.g., 'physics', 'literature', 'daily_use'", max_length=100)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='1=Basic, 5=Advanced')),
                ('pronunciation_english', models.CharField(blank=True, max_length=200)),
                ('pronunciation_bangla', models.CharField(blank=True, max_length=200)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Translation Dictionaries',
                'indexes': [models.Index(fields=['source_text', 'source_language'], name='translator__source__3ab9c7_idx'), models.Index(fields=['target_text', 'target_language'], name='translator__target__c99b4b_idx'), models.Index(fields=['word_type'], name='translator__word_ty_88bb32_idx'), models.Index(fields=['context'], name='translator__context_ccc603_idx')],
                'unique_together': {('source_text', 'source_language', 'target_language')},
            },
        ),
        migrations.CreateModel(
            name='TranslatorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_online', models.BooleanField(default=True)),
                ('total_translations', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=500)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], max_length=2)),
                ('translated_text', models.CharField(max_length=500)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], max_length=2)),
                ('context_type', models.CharField(default='general', help_text="e.g., 'study_session', 'notes', 'quiz_doubt'", max_length=50)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dictionary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_history', to='translator.translationdictionary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='translator__user_id_6c80f1_idx'), models.Index(fields=['source_language', 'target_language'], name='translator__source__cbb331_idx')],
            },
        ),
    ]
