# Generated by Django 4.2.27 on 2025-12-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai', '0003_alter_aichatmessage_id_alter_aichatsession_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='offlinenote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='remedialexplanation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini API'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Gemini → Ollama fallback)')], default='auto', help_text='Select which AI provider to use for all AI features', max_length=20)),
                ('ollama_base_url', models.CharField(default='http://51.21.208.44', help_text='Ollama server URL', max_length=255)),
                ('ollama_username', models.CharField(default='bipul', help_text='Ollama Basic Auth username', max_length=100)),
                ('ollama_password', models.CharField(default='Bipul$Ollama$Roy$2026$', help_text='Ollama Basic Auth password', max_length=255)),
                ('ollama_model', models.CharField(default='llama3', help_text='Ollama model name', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Provider Settings',
                'verbose_name_plural': 'AI Provider Settings',
            },
        ),
    ]
