# Generated by Django 6.0.4 on 2026-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_aichatmessage_id_alter_aichatsession_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Gemini API'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='Select which AI provider to use for all AI features', max_length=20),
        ),
        migrations.AlterField(
            model_name='offlinenote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='remedialexplanation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
