# Generated by Django 6.0.4 on 2026-04-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_aichatmessage_id_alter_aichatsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='alibaba_api_key',
            field=models.CharField(blank=True, help_text='Alibaba Cloud DashScope API Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='Google Gemini API Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='groq_api_key',
            field=models.CharField(blank=True, help_text='Groq API Key', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='Select which AI provider to use for all AI features', max_length=20),
        ),
    ]
