# Generated by Django 6.0.4 on 2026-04-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_aiprovidersettings_alibaba_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='doc_vision_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='gemini', help_text='AI Model Provider for processing PDFs, Documents, and Images (Vision).', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='general_chat_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='AI Model Provider for General Text Chat and Note taking.', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='quiz_flashcard_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='AI Model Provider for generating Quizzes and Flashcards.', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='study_plan_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='AI Model Provider for generating Study Plans and Suggestions.', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='AI Model Provider for AI Voice Tutor and Conversation.', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini API'), ('groq', 'Groq API'), ('alibaba', 'Alibaba Cloud (Qwen)'), ('ollama', 'Ollama (AWS)'), ('auto', 'Auto (Groq → Gemini fallback)')], default='auto', help_text='Select which AI provider to use as the default/global fallback.', max_length=20),
        ),
    ]
