# Generated by Django 6.0.4 on 2026-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_aiprovidersettings_doc_vision_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='elevenlabs_api_key',
            field=models.CharField(blank=True, help_text='API Key for ElevenLabs Voice Synthesis (leave blank to use browser native voice)', max_length=255, null=True),
        ),
    ]
