# Generated by Django 6.0.4 on 2026-04-11 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_aiprovidersettings_elevenlabs_api_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('tutor', 'AI Tutor (Ask Doubts)'), ('exam', 'Voice Exam Mode'), ('quiz', 'Voice Quiz/Practice'), ('general', 'General Chat')], default='tutor', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation_summary', models.TextField(blank=True, help_text='Auto-generated summary of the conversation', null=True)),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Key learning points from the conversation')),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('previous_session_context', models.TextField(blank=True, help_text='Summary from previous similar sessions for AI context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(help_text='Transcribed or typed message text')),
                ('message_type', models.CharField(choices=[('question', 'Question/Doubt'), ('answer', 'AI Answer'), ('quiz_question', 'Quiz Question'), ('quiz_answer', 'User Quiz Answer'), ('explanation', 'Explanation'), ('feedback', 'Feedback')], default='question', max_length=20)),
                ('is_user_message', models.BooleanField(default=True)),
                ('audio_url', models.URLField(blank=True, help_text='URL to audio file if recorded', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Transcription of voice message', null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in answer (0-1)')),
                ('is_correct', models.BooleanField(blank=True, help_text='For quiz mode - was answer correct?', null=True)),
                ('quiz_question_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.voiceconversationsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(help_text='AI-generated summary of the conversation')),
                ('key_concepts', models.JSONField(default=list, help_text='Key concepts discussed')),
                ('doubts_cleared', models.JSONField(default=list, help_text='Doubts/questions that were addressed')),
                ('next_topics_to_study', models.JSONField(default=list, help_text='AI recommendations for next topics')),
                ('learning_insights', models.TextField(blank=True, help_text="Personalized insights about student's learning", null=True)),
                ('weak_concepts', models.JSONField(default=list, help_text='Topics student struggled with')),
                ('strong_concepts', models.JSONField(default=list, help_text='Topics student understood well')),
                ('study_recommendations', models.TextField(blank=True, help_text="AI's recommendations for improvement", null=True)),
                ('practice_questions_suggested', models.JSONField(default=list, help_text='Practice questions to reinforce learning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_summaries', to=settings.AUTH_USER_MODEL)),
                ('voice_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='ai.voiceconversationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('practice', 'Practice Quiz'), ('exam', 'Exam Mode'), ('adaptive', 'Adaptive Quiz'), ('custom', 'Custom Topic Quiz')], default='practice', max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('class_level', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('performance_analysis', models.TextField(blank=True, help_text="AI's analysis of student performance", null=True)),
                ('weak_areas', models.JSONField(blank=True, default=list, help_text='Topics where student struggled')),
                ('strong_areas', models.JSONField(blank=True, default=list, help_text='Topics where student excelled')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.voiceconversationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='Sequence number in quiz')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer'), ('long', 'Long Answer'), ('calculation', 'Calculation/Problem')], default='mcq', max_length=20)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('correct_answer', models.TextField(blank=True, help_text='Expected/model answer for evaluation', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Detailed explanation for the answer', null=True)),
                ('question_audio_url', models.URLField(blank=True, help_text='Audio file of spoken question', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai.voicequizsession')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('typed', 'Typed'), ('spoken', 'Voice Transcribed'), ('selected', 'Multiple Choice Selection')], max_length=20)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, help_text='Transcription of voice answer', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_points', models.FloatField(default=0.0)),
                ('ai_evaluation', models.TextField(blank=True, help_text="AI's evaluation and feedback on answer", null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in evaluation (0-1)')),
                ('time_taken_seconds', models.IntegerField(help_text='Time user spent on this question')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai.voicequizquestion')),
            ],
            options={
                'ordering': ['answered_at'],
                'unique_together': {('quiz_question', 'user')},
            },
        ),
    ]
