# Generated by Django 6.0.4 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_voiceconversationsession_voiceconversationmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='flashcard_alibaba_extra_keys',
            field=models.TextField(blank=True, help_text='Optional extra Alibaba API keys for quiz/flashcard generation. Use comma or newline to separate multiple keys.', null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='flashcard_gemini_extra_keys',
            field=models.TextField(blank=True, help_text='Optional extra Gemini API keys for quiz/flashcard generation. Use comma or newline to separate multiple keys.', null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='flashcard_groq_extra_keys',
            field=models.TextField(blank=True, help_text='Optional extra Groq API keys for quiz/flashcard generation. Use comma or newline to separate multiple keys.', null=True),
        ),
    ]
