# Generated by Django 6.0.4 on 2026-04-14 00:00

from django.db import migrations, models


PROVIDER_CHOICES = [
    ('gemini', 'Google Gemini API'),
    ('groq', 'Groq API'),
    ('alibaba', 'Alibaba Cloud (Qwen)'),
    ('elevenlabs', 'ElevenLabs (voice-first; text with fallback)'),
    ('ollama', 'Ollama (AWS)'),
    ('auto', 'Auto (Groq → Gemini fallback)'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_aiprovidersettings_flashcard_extra_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='provider_used',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='chat_page_provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='auto',
                help_text='AI Model Provider for the /chat page AI assistant with provider fallback.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='auto',
                help_text='Select which AI provider to use as the default/global fallback.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='voice_ai_provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='auto',
                help_text='AI Model Provider for AI Voice Tutor and Conversation.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='study_plan_provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='auto',
                help_text='AI Model Provider for generating Study Plans and Suggestions.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='quiz_flashcard_provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='auto',
                help_text='AI Model Provider for generating Quizzes and Flashcards.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='doc_vision_provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='gemini',
                help_text='AI Model Provider for processing PDFs, Documents, and Images (Vision).',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='aiprovidersettings',
            name='general_chat_provider',
            field=models.CharField(
                choices=PROVIDER_CHOICES,
                default='auto',
                help_text='AI Model Provider for General Text Chat and Note taking.',
                max_length=20,
            ),
        ),
    ]
