# Generated by Django 6.0.4 on 2026-04-15 00:00

from django.db import migrations, models


VOICE_LLM_PROVIDER_CHOICES = [
    ('auto', 'Auto (Alibaba Qwen -> Groq fallback)'),
    ('alibaba', 'Alibaba Qwen'),
    ('groq', 'Groq'),
]

VOICE_STT_PROVIDER_CHOICES = [
    ('auto', 'Auto (Deepgram -> Sarvam fallback)'),
    ('deepgram', 'Deepgram'),
    ('sarvam', 'Sarvam AI'),
]

VOICE_TTS_PROVIDER_CHOICES = [
    ('auto', 'Auto (Gemini TTS -> Sarvam fallback)'),
    ('gemini', 'Gemini TTS'),
    ('sarvam', 'Sarvam AI TTS'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_aiprovidersettings_chat_page_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepgram_api_key',
            field=models.CharField(
                blank=True,
                help_text='Deepgram API key for speech-to-text.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='sarvam_api_key',
            field=models.CharField(
                blank=True,
                help_text='Sarvam AI API key for STT/TTS fallback.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_llm_provider',
            field=models.CharField(
                choices=VOICE_LLM_PROVIDER_CHOICES,
                default='auto',
                help_text='LLM provider for real-time AI voice tutor responses.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_stt_provider',
            field=models.CharField(
                choices=VOICE_STT_PROVIDER_CHOICES,
                default='auto',
                help_text='Speech-to-text provider for real-time AI voice tutor.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_tts_provider',
            field=models.CharField(
                choices=VOICE_TTS_PROVIDER_CHOICES,
                default='auto',
                help_text='Text-to-speech provider for real-time AI voice tutor.',
                max_length=20,
            ),
        ),
    ]
