# Generated by Django 5.1.5 on 2026-04-17 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0013_providersettings_conversationthread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepgram_stt_language',
            field=models.CharField(default='bn', help_text='Deepgram language code for STT (example: bn).', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepgram_stt_model',
            field=models.CharField(default='general', help_text='Deepgram STT model name.', max_length=60),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepgram_stt_tier',
            field=models.CharField(blank=True, default='nova-3', help_text='Optional Deepgram STT tier (example: nova-3).', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='deepgram_stt_url',
            field=models.URLField(blank=True, default='https://api.deepgram.com/v1/listen', help_text='Deepgram STT endpoint URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='gemini_tts_url',
            field=models.URLField(blank=True, default='https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-tts:generateContent', help_text='Gemini TTS endpoint URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='gemini_tts_voice',
            field=models.CharField(default='Kore', help_text='Gemini TTS voice profile name.', max_length=60),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='sarvam_stt_language',
            field=models.CharField(default='bn-IN', help_text='Sarvam STT language code.', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='sarvam_stt_url',
            field=models.URLField(blank=True, default='https://api.sarvam.ai/speech-to-text', help_text='Sarvam STT endpoint URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='sarvam_tts_language',
            field=models.CharField(default='bn-IN', help_text='Sarvam TTS target language code.', max_length=20),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='sarvam_tts_speaker',
            field=models.CharField(default='anushka', help_text='Sarvam TTS speaker voice name.', max_length=60),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='sarvam_tts_url',
            field=models.URLField(blank=True, default='https://api.sarvam.ai/text-to-speech', help_text='Sarvam TTS endpoint URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_fast_mode',
            field=models.BooleanField(default=True, help_text='Prefer faster model behavior and shorter response output for voice calls.'),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_force_bangla',
            field=models.BooleanField(default=True, help_text='Keep voice tutor responses in Bangla-first style.'),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_llm_provider_order',
            field=models.CharField(default='groq,alibaba', help_text='Fallback order for LLM providers. Comma-separated (example: groq,alibaba).', max_length=80),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_llm_timeout_seconds',
            field=models.PositiveIntegerField(default=45, help_text='Network timeout for LLM generation requests.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_response_max_chars',
            field=models.PositiveIntegerField(default=520, help_text='Maximum response length for voice replies to keep TTS fast.', validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_stt_provider_order',
            field=models.CharField(default='deepgram,sarvam', help_text='Fallback order for STT providers. Comma-separated (example: deepgram,sarvam).', max_length=80),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_stt_timeout_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Network timeout for STT requests.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_tts_provider_order',
            field=models.CharField(default='sarvam,gemini', help_text='Fallback order for TTS providers. Comma-separated (example: sarvam,gemini).', max_length=80),
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='voice_tts_timeout_seconds',
            field=models.PositiveIntegerField(default=35, help_text='Network timeout for TTS synthesis requests.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
