# Generated by Django 6.0.4 on 2026-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0014_aiprovidersettings_deepgram_stt_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='srijonshil_provider',
            field=models.CharField(
                choices=[
                    ('gemini', 'Google Gemini API'),
                    ('groq', 'Groq API'),
                    ('alibaba', 'Alibaba Cloud (Qwen)'),
                    ('elevenlabs', 'ElevenLabs (voice-first; text with fallback)'),
                    ('ollama', 'Ollama (AWS)'),
                    ('auto', 'Auto (Groq → Gemini fallback)'),
                ],
                default='auto',
                help_text='AI Model Provider for generating and evaluating Srijonshil question sets.',
                max_length=20,
            ),
        ),
    ]
