# Generated by Django 4.2.27 on 2025-12-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.IntegerField(choices=[(6, 'Class 6'), (7, 'Class 7'), (8, 'Class 8'), (9, 'Class 9'), (10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')])),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('english', 'English'), ('bangla', 'Bangla'), ('ict', 'ICT'), ('general_knowledge', 'General Knowledge')], max_length=50)),
                ('chapter_title', models.CharField(max_length=200)),
                ('chapter_description', models.TextField(blank=True)),
                ('page_range', models.CharField(blank=True, max_length=50)),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_level', 'subject', 'id'],
                'unique_together': {('class_level', 'subject', 'chapter_title')},
            },
        ),
    ]
