# Generated by Django 4.2.27 on 2025-12-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_id_alter_bookmark_id_alter_syllabus_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['class_level', 'subject', 'chapter_number']},
        ),
        migrations.AddField(
            model_name='syllabus',
            name='chapter_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_image',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus/images/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_pdf',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/pdfs/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
