# Generated by Django 4.2.27 on 2025-12-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_syllabus_options_syllabus_chapter_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
