from django.db import models
from accounts.models import User

class Subject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='subjects')
    name = models.CharField(max_length=100)
    color_code = models.CharField(max_length=20, default="#3B82F6", help_text="Hex color code for charts")
    icon = models.CharField(max_length=50, blank=True, null=True, help_text="Icon classes like 'fa-solid fa-book'")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.name}"
    
    @property
    def progress_percentage(self):
        total_topics = self.topics.count()
        if total_topics == 0:
            return 0
        completed = self.topics.filter(status='completed').count()
        return int((completed / total_topics) * 100)


class SyllabusTopic(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('need_revision', 'Needs Revision')
    ]

    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='topics')
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    is_important = models.BooleanField(default=False)
    order_index = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['order_index', 'created_at']

    def __str__(self):
        return f"{self.subject.name} - {self.title} ({self.get_status_display()})"


class StudyPlan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='study_plans')
    title = models.CharField(max_length=200, default="My AI Study Plan")
    target_exam_date = models.DateField(blank=True, null=True)
    ai_prompt_used = models.TextField(blank=True, null=True)
    plan_content = models.TextField(help_text="Markdown or JSON generated by AI")
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username}'s Plan: {self.title}"


class FlashcardDeck(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='flashcard_decks')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.title}"


class Flashcard(models.Model):
    deck = models.ForeignKey(FlashcardDeck, on_delete=models.CASCADE, related_name='cards')
    front = models.TextField(help_text="Question or concept")
    back = models.TextField(help_text="Answer or explanation")
    is_known = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.deck.title}: {self.front[:30]}..."


class FlashcardDeck(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='flashcard_decks')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username} - {self.title}"


class Flashcard(models.Model):
    deck = models.ForeignKey(FlashcardDeck, on_delete=models.CASCADE, related_name='cards')
    front = models.TextField(help_text="Question or concept")
    back = models.TextField(help_text="Answer or explanation")
    is_known = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.deck.title}: {self.front[:30]}..."
